
package org.example.mywsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMyService", targetNamespace = "http://www.example.org/mywsdl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMyService {


    /**
     * 
     * @param b
     * @param a
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "addResult", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://www.example.org/mywsdl/", className = "org.example.mywsdl.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://www.example.org/mywsdl/", className = "org.example.mywsdl.AddResponse")
    public int add(
            @WebParam(name = "a", targetNamespace = "")
                    int a,
            @WebParam(name = "b", targetNamespace = "")
                    int b);

    /**
     * 
     * @param d
     * @param c
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "minusResult", targetNamespace = "")
    @RequestWrapper(localName = "minus", targetNamespace = "http://www.example.org/mywsdl/", className = "org.example.mywsdl.Minus")
    @ResponseWrapper(localName = "minusResponse", targetNamespace = "http://www.example.org/mywsdl/", className = "org.example.mywsdl.MinusResponse")
    public int minus(
            @WebParam(name = "c", targetNamespace = "")
                    int c,
            @WebParam(name = "d", targetNamespace = "")
                    int d);

}
